-- Acrónimo de acuerdo al sistema
-- Nisum --> NSM

CREATE TABLE NSM_USER
(
    USR_ID           VARCHAR(36)  NOT NULL,
    USR_NAME         VARCHAR(100) NOT NULL,
    USR_EMAIL        VARCHAR(100) NOT NULL,
    USR_PASSWORD     VARCHAR(75)  NOT NULL,
    USR_STATUS       TINYINT      NOT NULL,
    USR_LAST_LOGIN   DATETIME DEFAULT CURRENT_TIMESTAMP(),
    USR_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    USR_DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    USR_USER_CREATED VARCHAR(100) NOT NULL,
    USR_USER_UPDATED VARCHAR(100) NOT NULL,
    PRIMARY KEY (USR_ID)
);

CREATE TABLE NSM_PHONE
(
    POE_ID           VARCHAR(36)  NOT NULL,
    POE_NUMBER       VARCHAR(15)  NOT NULL,
    POE_CITY_CODE    INT          NOT NULL,
    POE_COUNTRY_CODE INT          NOT NULL,
    POE_USR_ID       VARCHAR(36),
    POE_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    POE_DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    POE_USER_CREATED VARCHAR(100) NOT NULL,
    POE_USER_UPDATED VARCHAR(100) NOT NULL,
    PRIMARY KEY (POE_ID),
    FOREIGN KEY (POE_USR_ID) REFERENCES NSM_USER (USR_ID)
);

CREATE TABLE NSM_ROLE
(
    ROL_ID           VARCHAR(36)  NOT NULL,
    ROL_NAME         VARCHAR(20)  NOT NULL,
    ROL_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    ROL_DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    ROL_USER_CREATED VARCHAR(100) NOT NULL,
    ROL_USER_UPDATED VARCHAR(100) NOT NULL,
    PRIMARY KEY (ROL_ID)
);

CREATE TABLE NSM_USER_IN_ROLE
(
    UIR_ID           VARCHAR(36) AUTO_INCREMENT,
    UIR_USR_ID       VARCHAR(36),
    UIR_ROL_ID       VARCHAR(36),
    UIR_DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP(),
    UIR_DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (UIR_ID),
    FOREIGN KEY (UIR_USR_ID) REFERENCES NSM_USER (USR_ID),
    FOREIGN KEY (UIR_ROL_ID) REFERENCES NSM_ROLE (ROL_ID)
);

